//! M55 — `ray templ`: templates compilados. Un `.ray.html` con `{% params %}` tipados se compila a
//! un módulo raylang (`pub fn render_<stem>(…) -> string`) que se importa como cualquier módulo.
//! El test genera el módulo, corre un programa que lo usa (golden por AMBOS motores: autoescape,
//! elif, for sobre arreglo y sobre rango, expresiones `{{ n * 10 }}`, literales con `${`/comillas),
//! verifica que un typo en una variable es ERROR DE COMPILACIÓN (la promesa del diseño), y cubre
//! los errores del propio template (sin params, endif faltante, etiqueta desconocida).

use std::process::Command;

const BIN: &str = env!("CARGO_BIN_EXE_raylang");

const TPL: &str = r#"{% params titulo: string, admin: bool, filas: [string], total: int %}
<html><body>
<h1>{{ titulo }}</h1>
{% if admin %}<p>mode admin</p>{% elif total > 0 %}<p>{{ total }} filas</p>{% else %}<p>vacío</p>{% endif %}
<ul>{% for row in filas %}<li>{{ row }}</li>{% endfor %}</ul>
<p>precio: "${simbolo}" & <raro></p>
{% for i in 0..2 %}[{{ i * 10 }}]{% endfor %}
</body></html>
"#;

const MAIN: &str = r#"import vistas/list;

fn main() -> int {
    print(list.render_list("Informe & data", false, ["a<b", "c"], 2));
    0
}
"#;

const EXPECTED: &str = "<html><body>\n\
<h1>Informe &amp; data</h1>\n\
<p>2 filas</p>\n\
<ul><li>a&lt;b</li><li>c</li></ul>\n\
<p>precio: \"${simbolo}\" & <raro></p>\n\
[0][10]\n\
</body></html>\n\n";

fn project(base: &std::path::Path, tpl: &str, main: &str) -> std::path::PathBuf {
    let app = base.join("app");
    std::fs::create_dir_all(app.join("vistas")).unwrap();
    std::fs::write(app.join("vistas/list.ray.html"), tpl).unwrap();
    std::fs::write(app.join("main.ray"), main).unwrap();
    app
}

fn templ(app: &std::path::Path, arg: &str) -> (String, String, i32) {
    let out = Command::new(BIN).args(["templ", arg]).current_dir(app).output().expect("lanza ray templ");
    (
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
        out.status.code().unwrap_or(-1),
    )
}


/// Dir temporal AUTO-LIMPIADO al salir del test (los `.ray.html` ROTOS que estos tests dejan a
/// propósito envenenaban el /tmp compartido: cualquier proceso que escanease templates desde ahí
/// —p. ej. un servidor MCP viejo— abortaba con un error ajeno).
struct TmpDir(std::path::PathBuf);
impl TmpDir {
    fn new(name: &str) -> Self {
        let d = std::env::temp_dir().join(name);
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).expect("crea el dir temporal");
        Self(d)
    }
}
impl std::ops::Deref for TmpDir {
    type Target = std::path::Path;
    fn deref(&self) -> &std::path::Path { &self.0 }
}
impl AsRef<std::path::Path> for TmpDir {
    fn as_ref(&self) -> &std::path::Path { &self.0 }
}
impl Drop for TmpDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

#[test]
fn generates_and_renders_on_both_engines() {
    let base = TmpDir::new("ray_templ_cli");
    let app = project(&base, TPL, MAIN);

    let (stdout, stderr, code) = templ(&app, "vistas");
    assert_eq!(code, 0, "ray templ fails:\n{stderr}");
    assert!(stdout.contains("generated:"), "{stdout}");
    let generated = std::fs::read_to_string(app.join("vistas/list.ray")).unwrap();
    assert!(generated.contains("pub fn render_list(titulo: string, admin: bool, filas: [string], total: int) -> string"), "{generated}");
    assert!(generated.contains("GENERATED by `ray templ`"), "header de no-editar\n{generated}");

    // El módulo generado corre idéntico por ambos motores.
    for flags in [&[][..], &["--interp"][..]] {
        let mut args = vec!["run"];
        args.extend_from_slice(flags);
        args.push("main.ray");
        let out = Command::new(BIN).args(&args).current_dir(&app).output().unwrap();
        assert!(out.status.success(), "run fails ({flags:?}): {}", String::from_utf8_lossy(&out.stderr));
        assert_eq!(String::from_utf8_lossy(&out.stdout), EXPECTED, "({flags:?})");
    }
}

#[test]
fn a_typo_in_a_variable_is_a_compile_error() {
    // La promesa del diseño: `{{ titulo }}` mal escrito NO es un "" silencioso (como en el motor
    // runtime), sino un error de tipos del módulo generado al compilar el programa.
    let base = TmpDir::new("ray_templ_cli_typo");
    let tpl = "{% params titulo: string %}<h1>{{ titluo }}</h1>\n"; // typo: titluo
    let main = "import vistas/list;\n\nfn main() -> int {\n    print(list.render_list(\"x\"));\n    0\n}\n";
    let app = project(&base, tpl, main);

    let (_, stderr, code) = templ(&app, "vistas");
    assert_eq!(code, 0, "el template ES sintácticamente válido:\n{stderr}");
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(65), "must fallar la compilación");
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("titluo"), "el error señala el typo:\n{err}");
}

#[test]
fn run_and_build_regenerate_stale_templates() {
    // M55: `ray run`/`ray build` regeneran los `.ray.html` cuyo `.ray` falte o esté viejo — no hay
    // que acordarse de `ray templ`. El aviso va por stderr (stdout es del programa).
    let base = TmpDir::new("ray_templ_autoregen");
    let tpl = "{% params t: string %}<h1>{{ t }}</h1>\n";
    let main = "import vistas/list;\n\nfn main() -> int {\n    print(list.render_list(\"hello\"));\n    0\n}\n";
    let app = project(&base, tpl, main);

    // 1) Sin `ray templ` previo: el generado FALTA → `ray run` lo genera y el programa corre.
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    assert!(String::from_utf8_lossy(&out.stdout).contains("<h1>hello</h1>"));
    assert!(String::from_utf8_lossy(&out.stderr).contains("template regenerated"), "aviso por stderr");

    // 2) Editar el template → el generado queda VIEJO → `ray run` lo regenera solo.
    std::thread::sleep(std::time::Duration::from_millis(30)); // mtime estrictamente posterior
    std::fs::write(app.join("vistas/list.ray.html"), "{% params t: string %}<h2>{{ t }}</h2>\n").unwrap();
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    assert!(String::from_utf8_lossy(&out.stdout).contains("<h2>hello</h2>"), "runs el template NUEVO");

    // 3) Sin cambios: nada que regenerar (ni aviso).
    let out = Command::new(BIN).args(["build", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success());
    assert!(!String::from_utf8_lossy(&out.stderr).contains("regenerated"), "al día → silencio");

    // 4) Un template ROTO aborta el build con 65 y el error del template (mejor señal que
    //    compilar el generado viejo).
    std::thread::sleep(std::time::Duration::from_millis(30));
    std::fs::write(app.join("vistas/list.ray.html"), "{% params t: string %}{% if t %}sin cierre\n").unwrap();
    let out = Command::new(BIN).args(["build", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(65));
    assert!(String::from_utf8_lossy(&out.stderr).contains("endif"), "{}", String::from_utf8_lossy(&out.stderr));
    // Limpieza: el template ROTO no debe quedar en el /tmp compartido — otro test que resuelva una
    // entrada bajo temp_dir (p. ej. el `ray_check` del MCP) dispararía la regeneración sobre él y
    // fallaría con este 65 (flake real observado en la batería paralela).
    let _ = std::fs::remove_dir_all(&base);
}

#[test]
fn editing_the_layout_regenerates_views_that_extend_it() {
    // `{% extends %}` fusiona el layout EN COMPILACIÓN: su HTML vive dentro del `.ray` generado
    // del hijo. Editar solo el layout debe dejar VIEJO también el generado del hijo (antes solo
    // se comparaba cada template contra su propio `.ray` → el hijo servía el layout viejo).
    let base = TmpDir::new("ray_templ_layout_stale");
    let app = base.join("app");
    std::fs::create_dir_all(app.join("vistas")).unwrap();
    std::fs::write(app.join("ray.toml"), "[package]\nname = \"app\"\nversion = \"0.1.0\"\n").unwrap();
    std::fs::write(app.join("vistas/base.ray.html"),
        "{% params titulo: string %}<html><head><title>{{ titulo }}</title></head><body>{% block body %}{% endblock %}</body></html>\n").unwrap();
    std::fs::write(app.join("vistas/pagina.ray.html"),
        "{% params titulo: string %}\n{% extends vistas/base %}\n{% block body %}<h1>{{ titulo }}</h1>{% endblock %}\n").unwrap();
    std::fs::write(app.join("main.ray"),
        "import vistas/pagina;\n\nfn main() -> int {\n    print(pagina.render_pagina(\"hola\"));\n    0\n}\n").unwrap();

    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    assert!(String::from_utf8_lossy(&out.stdout).contains("<title>hola</title>"));

    // Editar SOLO el layout (añade un <style> al head) → el hijo debe regenerarse y servirlo.
    std::thread::sleep(std::time::Duration::from_millis(30)); // mtime estrictamente posterior
    std::fs::write(app.join("vistas/base.ray.html"),
        "{% params titulo: string %}<html><head><title>{{ titulo }}</title><style>body { margin: 0; }</style></head><body>{% block body %}{% endblock %}</body></html>\n").unwrap();
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("<style>body { margin: 0; }</style>"), "el hijo sirve el layout NUEVO:\n{stdout}");

    // Sin cambios: nada que regenerar.
    let out = Command::new(BIN).args(["build", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success());
    assert!(!String::from_utf8_lossy(&out.stderr).contains("regenerated"), "al día → silencio");
}

#[test]
fn include_and_import_compose_views_and_layout() {
    // Composición M55: una página {% import %}a un partial y lo {% include %}; un layout es un
    // template más con param `contenido: string` que envuelve lo ya renderizado.
    let base = TmpDir::new("ray_templ_include");
    let app = base.join("app");
    std::fs::create_dir_all(app.join("vistas")).unwrap();
    std::fs::write(app.join("vistas/tarjeta.ray.html"),
        "{% params name: string %}<div class=\"tarjeta\">{{ name }}</div>\n").unwrap();
    std::fs::write(app.join("vistas/layout.ray.html"),
        "{% params titulo: string, contenido: string %}<html><title>{{ titulo }}</title><body>{% include contenido %}</body></html>\n").unwrap();
    // El include por RUTA: sin `{% import %}` manual ni conocer el `render_<x>` generado.
    std::fs::write(app.join("vistas/pagina.ray.html"),
        "{% params names: [string] %}<ul>{% for n in names %}{% include vistas/tarjeta(n) %}{% endfor %}</ul>\n").unwrap();
    std::fs::write(app.join("main.ray"),
        "import vistas/pagina;\nimport vistas/layout;\n\nfn main() -> int {\n    print(layout.render_layout(\"Equipo\", pagina.render_pagina([\"Ada\", \"Lin<us\"])));\n    0\n}\n").unwrap();

    // Sin `ray templ` explícito: la regeneración automática de `ray run` compila los tres.
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    let expected = "<html><title>Equipo</title><body><ul>\
        <div class=\"tarjeta\">Ada</div>\n\
        <div class=\"tarjeta\">Lin&lt;us</div>\n\
        </ul>\n</body></html>\n\n";
    assert_eq!(stdout, expected, "el include NO re-escapa el HTML del partial, pero el partial SÍ escapó su dato");
}

#[test]
fn extends_block_y_let_end_to_end() {
    // Herencia de layout estilo Jinja (M55): el hijo `{% extends base %}` + `{% block %}`s; el
    // layout pone la estructura (con defaults) y compila también standalone. `{% let %}` declara
    // locales del template.
    let base = TmpDir::new("ray_templ_extends");
    let app = base.join("app");
    std::fs::create_dir_all(app.join("vistas")).unwrap();
    std::fs::write(app.join("vistas/base.ray.html"),
        "{% params titulo: string %}<html><title>{{ titulo }}</title><body>{% block body %}<p>vacío</p>{% endblock %}<footer>{% block pie %}© raylang{% endblock %}</footer></body></html>\n").unwrap();
    std::fs::write(app.join("vistas/pagina.ray.html"),
        "{% params titulo: string, precios: [int] %}\n{% extends base %}\n{% block body %}{% let cuantos = precios.len() %}<p>{{ cuantos }} precios</p>{% endblock %}\n").unwrap();
    std::fs::write(app.join("main.ray"),
        "import vistas/pagina;\n\nfn main() -> int {\n    print(pagina.render_pagina(\"Lista\", [1, 2, 3]));\n    0\n}\n").unwrap();

    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert_eq!(stdout, "<html><title>Lista</title><body><p>3 precios</p><footer>© raylang</footer></body></html>\n\n",
        "hereda la estructura, sobreescribe `body`, conserva el default de `pie`");

    // Un typo en el nombre del bloque es error de compilación con SU línea.
    std::thread::sleep(std::time::Duration::from_millis(30));
    std::fs::write(app.join("vistas/pagina.ray.html"),
        "{% params titulo: string %}\n{% extends base %}\n{% block cuerpu %}x{% endblock %}\n").unwrap();
    let out = Command::new(BIN).args(["build", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(65));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("does not declare") && err.contains("cuerpu"), "{err}");
}

#[test]
fn errors_del_template() {
    let base = TmpDir::new("ray_templ_cli_err");

    let cases: &[(&str, &str)] = &[
        ("<h1>hello</h1>", "params"),                                    // sin firma
        ("{% params x: int %}{% if x > 0 %}abierto", "endif"),          // sin cerrar
        ("{% params x: int %}{% zzz %}", "unknown"),             // etiqueta inválida
        ("{% params x %}hello", "malformed"),                          // params sin tipo
    ];
    let mut k = 0;
    for (tpl, espera) in cases {
        let app = base.join(format!("case{k}"));
        std::fs::create_dir_all(app.join("vistas")).unwrap();
        std::fs::write(app.join("vistas/v.ray.html"), tpl).unwrap();
        let (_, stderr, code) = templ(&app, "vistas");
        assert_eq!(code, 65, "case {k} debía fallar:\n{stderr}");
        assert!(stderr.contains(espera), "case {k}: esperaba '{espera}' en:\n{stderr}");
        k += 1;
    }
}
