//! M55 — `ray build --templates-only`: templates compilados. Un `.ray.html` con `{% params %}` tipados se compila a
//! un módulo raylang (`pub fn render_<stem>(…) -> string`) que se importa como cualquier módulo.
//! El test genera el módulo, corre un programa que lo usa (golden por AMBOS motores: autoescape,
//! elif, for sobre arreglo y sobre rango, expresiones `{{ n * 10 }}`, literales con `${`/comillas),
//! verifica que un typo en una variable es ERROR DE COMPILACIÓN (la promesa del diseño), y cubre
//! los errores del propio template (sin params, endif faltante, etiqueta desconocida).

use std::process::Command;

const BIN: &str = env!("CARGO_BIN_EXE_raylang");

const TPL: &str = r#"{% params titulo: string, admin: bool, filas: [string], total: int %}
<html><body>
<h1>{{ titulo }}</h1>
{% if admin %}<p>mode admin</p>{% elif total > 0 %}<p>{{ total }} filas</p>{% else %}<p>vacío</p>{% endif %}
<ul>{% for row in filas %}<li>{{ row }}</li>{% endfor %}</ul>
<p>precio: "${simbolo}" & <raro></p>
{% for i in 0..2 %}[{{ i * 10 }}]{% endfor %}
</body></html>
"#;

const MAIN: &str = r#"import vistas/list;

fn main() -> int {
    print(list.render_list("Informe & data", false, ["a<b", "c"], 2));
    0
}
"#;

const EXPECTED: &str = "<html><body>\n\
<h1>Informe &amp; data</h1>\n\
<p>2 filas</p>\n\
<ul><li>a&lt;b</li><li>c</li></ul>\n\
<p>precio: \"${simbolo}\" & <raro></p>\n\
[0][10]\n\
</body></html>\n\n";

fn project(base: &std::path::Path, tpl: &str, main: &str) -> std::path::PathBuf {
    let app = base.join("app");
    std::fs::create_dir_all(app.join("vistas")).unwrap();
    std::fs::write(app.join("vistas/list.ray.html"), tpl).unwrap();
    std::fs::write(app.join("main.ray"), main).unwrap();
    app
}

fn templ(app: &std::path::Path, arg: &str) -> (String, String, i32) {
    let out = Command::new(BIN)
        .args(["build", "--templates-only", arg])
        .current_dir(app)
        .output()
        .expect("lanza ray build --templates-only");
    (
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
        out.status.code().unwrap_or(-1),
    )
}


/// Dir temporal AUTO-LIMPIADO al salir del test (los `.ray.html` ROTOS que estos tests dejan a
/// propósito envenenaban el /tmp compartido: cualquier proceso que escanease templates desde ahí
/// —p. ej. un servidor MCP viejo— abortaba con un error ajeno).
struct TmpDir(std::path::PathBuf);
impl TmpDir {
    fn new(name: &str) -> Self {
        let d = std::env::temp_dir().join(name);
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).expect("crea el dir temporal");
        Self(d)
    }
}
impl std::ops::Deref for TmpDir {
    type Target = std::path::Path;
    fn deref(&self) -> &std::path::Path { &self.0 }
}
impl AsRef<std::path::Path> for TmpDir {
    fn as_ref(&self) -> &std::path::Path { &self.0 }
}
impl Drop for TmpDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

#[test]
fn generates_and_renders_on_both_engines() {
    let base = TmpDir::new("ray_templ_cli");
    let app = project(&base, TPL, MAIN);

    let (stdout, stderr, code) = templ(&app, "vistas");
    assert_eq!(code, 0, "ray build --templates-only fails:\n{stderr}");
    assert!(stdout.contains("generated:"), "{stdout}");
    let generated = std::fs::read_to_string(app.join("vistas/list.ray")).unwrap();
    assert!(generated.contains("pub fn render_list(titulo: string, admin: bool, filas: [string], total: int) -> string"), "{generated}");
    assert!(generated.contains("GENERATED by `ray build --templates-only`"), "header de no-editar\n{generated}");

    // El módulo generado corre idéntico por ambos motores.
    for flags in [&[][..], &["--interp"][..]] {
        let mut args = vec!["run"];
        args.extend_from_slice(flags);
        args.push("main.ray");
        let out = Command::new(BIN).args(&args).current_dir(&app).output().unwrap();
        assert!(out.status.success(), "run fails ({flags:?}): {}", String::from_utf8_lossy(&out.stderr));
        assert_eq!(String::from_utf8_lossy(&out.stdout), EXPECTED, "({flags:?})");
    }
}

#[test]
fn a_typo_in_a_variable_is_a_compile_error() {
    // La promesa del diseño: `{{ titulo }}` mal escrito NO es un "" silencioso (como en el motor
    // runtime), sino un error de tipos del módulo generado al compilar el programa.
    let base = TmpDir::new("ray_templ_cli_typo");
    let tpl = "{% params titulo: string %}<h1>{{ titluo }}</h1>\n"; // typo: titluo
    let main = "import vistas/list;\n\nfn main() -> int {\n    print(list.render_list(\"x\"));\n    0\n}\n";
    let app = project(&base, tpl, main);

    let (_, stderr, code) = templ(&app, "vistas");
    assert_eq!(code, 0, "el template ES sintácticamente válido:\n{stderr}");
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(65), "must fallar la compilación");
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("titluo"), "el error señala el typo:\n{err}");
}

#[test]
fn run_and_build_compile_templates_in_memory() {
    // M102: el loader compila cada `.ray.html` EN MEMORIA al resolver su import — sin `.ray`
    // generado en el proyecto, sin staleness por mtime, sin avisos de regeneración.
    let base = TmpDir::new("ray_templ_in_memory");
    let tpl = "{% params t: string %}<h1>{{ t }}</h1>\n";
    let main = "import vistas/list;\n\nfn main() -> int {\n    print(list.render_list(\"hello\"));\n    0\n}\n";
    let app = project(&base, tpl, main);

    // 1) Sin `ray build --templates-only`: el programa corre y NO aparece ningún `.ray` generado.
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    assert!(String::from_utf8_lossy(&out.stdout).contains("<h1>hello</h1>"));
    assert!(!app.join("vistas/list.ray").exists(), "no debe materializar el generado");
    assert!(!String::from_utf8_lossy(&out.stderr).contains("regenerated"), "sin avisos de regen");

    // 2) Editar el template → el siguiente run sirve lo NUEVO (no hay artefacto que caduque).
    std::fs::write(app.join("vistas/list.ray.html"), "{% params t: string %}<h2>{{ t }}</h2>\n").unwrap();
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    assert!(String::from_utf8_lossy(&out.stdout).contains("<h2>hello</h2>"), "runs el template NUEVO");

    // 3) Un template ROTO aborta el build con 65 y el error del template (archivo + línea).
    std::fs::write(app.join("vistas/list.ray.html"), "{% params t: string %}{% if t %}sin cierre\n").unwrap();
    let out = Command::new(BIN).args(["build", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(65));
    assert!(String::from_utf8_lossy(&out.stderr).contains("endif"), "{}", String::from_utf8_lossy(&out.stderr));
}

#[test]
fn diagnostics_point_to_the_template_line() {
    // M102-A2: el generado no existe en disco, así que TODO diagnóstico de un módulo-template se
    // traduce por el line map a la línea del `.ray.html` (a nivel de línea: col 1, subrayado
    // completo) y se renderiza contra el fuente del TEMPLATE, no contra el generado invisible.
    let base = TmpDir::new("ray_templ_diag_lines");
    let main = "import vistas/list;\n\nfn main() -> int {\n    print(list.render_list(\"x\"));\n    0\n}\n";

    // 1) Error de TIPOS (el typo clásico): línea 3 del template, con su fuente.
    let app = project(&base, "{% params titulo: string %}\n<html>\n<h1>{{ titluo }}</h1>\n</html>\n", main);
    let out = Command::new(BIN).args(["build", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(65));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("type error at 3:1"), "la cabecera lleva la línea del TEMPLATE:\n{err}");
    assert!(err.contains("<h1>{{ titluo }}</h1>"), "se muestra el fuente del template:\n{err}");

    // 2) Expresión empalmada MAL FORMADA: el error de sintaxis del generado vuelve al template.
    std::fs::write(app.join("vistas/list.ray.html"), "{% params titulo: string %}\n<p>{{ 1 + }}</p>\n").unwrap();
    let out = Command::new(BIN).args(["build", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(65));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("syntax error at 2:1"), "{err}");
    assert!(err.contains("<p>{{ 1 + }}</p>"), "{err}");

    // 3) Error de RUNTIME dentro del template: cabecera y traza con la línea del template.
    std::fs::write(app.join("vistas/list.ray.html"),
        "{% params titulo: string %}\n<ol>\n<li>{{ [1,2,3][9] }}</li>\n</ol>\n").unwrap();
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(70));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("runtime error at 3:1"), "{err}");
    assert!(err.contains("<li>{{ [1,2,3][9] }}</li>"), "{err}");
    assert!(err.contains("(vistas/list:3:1)"), "la traza también traduce:\n{err}");

    // 4) Include de un template INEXISTENTE: el import generado no existe en el template; el
    //    error apunta a la línea del {% include %}.
    std::fs::write(app.join("vistas/list.ray.html"),
        "{% params titulo: string %}\n<div>\n{% include vistas/typo(titulo) %}\n</div>\n").unwrap();
    let out = Command::new(BIN).args(["build", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(65));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("module 'vistas/typo' not found"), "{err}");
    assert!(err.contains("{% include vistas/typo(titulo) %}"), "{err}");
}

#[test]
fn a_stale_generated_sibling_is_ignored() {
    // M102: si junto al template queda un `.ray` generado viejo (de `ray build --templates-only`
    // o de un repo anterior a la compilación en memoria), el loader prefiere SIEMPRE el template.
    let base = TmpDir::new("ray_templ_stale_sibling");
    let tpl = "{% params t: string %}<h1>{{ t }}</h1>\n";
    let main = "import vistas/list;\n\nfn main() -> int {\n    print(list.render_list(\"hello\"));\n    0\n}\n";
    let app = project(&base, tpl, main);
    // Un hermano generado VIEJO y además ROTO: si el loader lo leyera, el build fallaría.
    std::fs::write(app.join("vistas/list.ray"), "this is not raylang {{{").unwrap();

    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    assert!(String::from_utf8_lossy(&out.stdout).contains("<h1>hello</h1>"), "gana el template");
}

#[test]
fn editing_the_layout_reaches_views_that_extend_it() {
    // `{% extends %}` fusiona el layout EN COMPILACIÓN: su HTML vive dentro del módulo generado
    // del hijo. Con la compilación en memoria (M102) no hay artefacto que caduque: editar solo el
    // layout debe verse en el siguiente run del hijo.
    let base = TmpDir::new("ray_templ_layout_edit");
    let app = base.join("app");
    std::fs::create_dir_all(app.join("vistas")).unwrap();
    std::fs::write(app.join("ray.toml"), "[package]\nname = \"app\"\nversion = \"0.1.0\"\n").unwrap();
    std::fs::write(app.join("vistas/base.ray.html"),
        "{% params titulo: string %}<html><head><title>{{ titulo }}</title></head><body>{% block body %}{% endblock %}</body></html>\n").unwrap();
    std::fs::write(app.join("vistas/pagina.ray.html"),
        "{% params titulo: string %}\n{% extends vistas/base %}\n{% block body %}<h1>{{ titulo }}</h1>{% endblock %}\n").unwrap();
    std::fs::write(app.join("main.ray"),
        "import vistas/pagina;\n\nfn main() -> int {\n    print(pagina.render_pagina(\"hola\"));\n    0\n}\n").unwrap();

    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    assert!(String::from_utf8_lossy(&out.stdout).contains("<title>hola</title>"));

    // Editar SOLO el layout (añade un <style> al head) → el hijo debe servirlo en el acto.
    std::fs::write(app.join("vistas/base.ray.html"),
        "{% params titulo: string %}<html><head><title>{{ titulo }}</title><style>body { margin: 0; }</style></head><body>{% block body %}{% endblock %}</body></html>\n").unwrap();
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("<style>body { margin: 0; }</style>"), "el hijo sirve el layout NUEVO:\n{stdout}");
}

#[test]
fn include_and_import_compose_views_and_layout() {
    // Composición M55: una página {% import %}a un partial y lo {% include %}; un layout es un
    // template más con param `contenido: string` que envuelve lo ya renderizado.
    let base = TmpDir::new("ray_templ_include");
    let app = base.join("app");
    std::fs::create_dir_all(app.join("vistas")).unwrap();
    std::fs::write(app.join("vistas/tarjeta.ray.html"),
        "{% params name: string %}<div class=\"tarjeta\">{{ name }}</div>\n").unwrap();
    std::fs::write(app.join("vistas/layout.ray.html"),
        "{% params titulo: string, contenido: string %}<html><title>{{ titulo }}</title><body>{% include contenido %}</body></html>\n").unwrap();
    // El include por RUTA: sin `{% import %}` manual ni conocer el `render_<x>` generado.
    std::fs::write(app.join("vistas/pagina.ray.html"),
        "{% params names: [string] %}<ul>{% for n in names %}{% include vistas/tarjeta(n) %}{% endfor %}</ul>\n").unwrap();
    std::fs::write(app.join("main.ray"),
        "import vistas/pagina;\nimport vistas/layout;\n\nfn main() -> int {\n    print(layout.render_layout(\"Equipo\", pagina.render_pagina([\"Ada\", \"Lin<us\"])));\n    0\n}\n").unwrap();

    // Sin `ray build --templates-only` explícito: el loader compila los tres en memoria (M102).
    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    let expected = "<html><title>Equipo</title><body><ul>\
        <div class=\"tarjeta\">Ada</div>\n\
        <div class=\"tarjeta\">Lin&lt;us</div>\n\
        </ul>\n</body></html>\n\n";
    assert_eq!(stdout, expected, "el include NO re-escapa el HTML del partial, pero el partial SÍ escapó su dato");
}

#[test]
fn extends_block_y_let_end_to_end() {
    // Herencia de layout estilo Jinja (M55): el hijo `{% extends base %}` + `{% block %}`s; el
    // layout pone la estructura (con defaults) y compila también standalone. `{% let %}` declara
    // locales del template.
    let base = TmpDir::new("ray_templ_extends");
    let app = base.join("app");
    std::fs::create_dir_all(app.join("vistas")).unwrap();
    std::fs::write(app.join("vistas/base.ray.html"),
        "{% params titulo: string %}<html><title>{{ titulo }}</title><body>{% block body %}<p>vacío</p>{% endblock %}<footer>{% block pie %}© raylang{% endblock %}</footer></body></html>\n").unwrap();
    std::fs::write(app.join("vistas/pagina.ray.html"),
        "{% params titulo: string, precios: [int] %}\n{% extends base %}\n{% block body %}{% let cuantos = precios.len() %}<p>{{ cuantos }} precios</p>{% endblock %}\n").unwrap();
    std::fs::write(app.join("main.ray"),
        "import vistas/pagina;\n\nfn main() -> int {\n    print(pagina.render_pagina(\"Lista\", [1, 2, 3]));\n    0\n}\n").unwrap();

    let out = Command::new(BIN).args(["run", "main.ray"]).current_dir(&app).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert_eq!(stdout, "<html><title>Lista</title><body><p>3 precios</p><footer>© raylang</footer></body></html>\n\n",
        "hereda la estructura, sobreescribe `body`, conserva el default de `pie`");

    // Un typo en el nombre del bloque es error de compilación con SU línea.
    std::thread::sleep(std::time::Duration::from_millis(30));
    std::fs::write(app.join("vistas/pagina.ray.html"),
        "{% params titulo: string %}\n{% extends base %}\n{% block cuerpu %}x{% endblock %}\n").unwrap();
    let out = Command::new(BIN).args(["build", "main.ray"]).current_dir(&app).output().unwrap();
    assert_eq!(out.status.code(), Some(65));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("does not declare") && err.contains("cuerpu"), "{err}");
}

#[test]
fn errors_del_template() {
    let base = TmpDir::new("ray_templ_cli_err");

    let cases: &[(&str, &str)] = &[
        ("<h1>hello</h1>", "params"),                                    // sin firma
        ("{% params x: int %}{% if x > 0 %}abierto", "endif"),          // sin cerrar
        ("{% params x: int %}{% zzz %}", "unknown"),             // etiqueta inválida
        ("{% params x %}hello", "malformed"),                          // params sin tipo
    ];
    let mut k = 0;
    for (tpl, espera) in cases {
        let app = base.join(format!("case{k}"));
        std::fs::create_dir_all(app.join("vistas")).unwrap();
        std::fs::write(app.join("vistas/v.ray.html"), tpl).unwrap();
        let (_, stderr, code) = templ(&app, "vistas");
        assert_eq!(code, 65, "case {k} debía fallar:\n{stderr}");
        assert!(stderr.contains(espera), "case {k}: esperaba '{espera}' en:\n{stderr}");
        k += 1;
    }
}
